FROM python:3.10

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

# Some packages will be built from source (e.g. duckdb) for arm64
# Include those packages in the base image to save time
COPY requirements/base-requirements.txt /tmp/base-requirements.txt
RUN pip install --no-cache-dir --timeout 1000 -r /tmp/base-requirements.txt

# Setting up docker in docker
RUN curl -fsSL https://get.docker.com | sh