"""sync schedules and sync runs models

Revision ID: 1fb208c0104d
Revises: 9d3ca3122d43
Create Date: 2023-03-09 07:48:25.243115

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fb208c0104d'
down_revision = '9d3ca3122d43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_schedules',
    sa.Column('sync_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_interval', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sync_id')
    )
    op.create_table('sync_runs',
    sa.Column('sync_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('run_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('run_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_status', sa.Text(), nullable=False),
    sa.Column('run_metrics', sa.JSON(), nullable=True),
    sa.Column('run_remarks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sync_id'], ['sync_schedules.sync_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_runs')
    op.drop_table('sync_schedules')
    # ### end Alembic commands ###
