"""generate migrations

Revision ID: 2d111153e4a3
Revises: 
Create Date: 2023-03-19 06:19:14.624559

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d111153e4a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_schedules',
    sa.Column('sync_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_run_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('run_interval', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('run_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sync_id')
    )
    op.create_table('sync_runs',
    sa.Column('sync_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('run_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('run_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('dagster_run_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sync_id'], ['sync_schedules.sync_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_runs')
    op.drop_table('sync_schedules')
    # ### end Alembic commands ###
