"""add index on sync_id and run_id for table sync_runs

Revision ID: 46c2a535e76f
Revises: 2d111153e4a3
Create Date: 2023-03-20 12:49:05.320588

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '46c2a535e76f'
down_revision = '2d111153e4a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_runs', sa.Column('run_time_args', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_runs', 'run_time_args')
    # ### end Alembic commands ###
