"""create inital tables

Revision ID: ac7bf454b166
Revises: e64091fc4e6f
Create Date: 2023-02-23 23:15:03.511843

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'ac7bf454b166'
down_revision = 'e64091fc4e6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
