"""add timestamp to store

Revision ID: b2fd7f76fa33
Revises: 7b8fdebf0bb2
Create Date: 2023-02-19 13:05:48.997615

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'b2fd7f76fa33'
down_revision = '7b8fdebf0bb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('name', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'name')
    # ### end Alembic commands ###
