"""add connector types for sync schedule

Revision ID: b8a04d6a2ce2
Revises: b38c0dca7de4
Create Date: 2023-06-01 21:04:50.324310

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'b8a04d6a2ce2'
down_revision = 'b38c0dca7de4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sync_runs', ['sync_id', 'run_id'])
    op.add_column('sync_schedules', sa.Column('src_connector_type', sa.Text(), nullable=False))
    op.add_column('sync_schedules', sa.Column('dst_connector_type', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_schedules', 'dst_connector_type')
    op.drop_column('sync_schedules', 'src_connector_type')
    op.drop_constraint(None, 'sync_runs', type_='unique')
    # ### end Alembic commands ###
