"""sync schedules and sync runs models revision

Revision ID: bb07e4fc3fe8
Revises: c720631c996d
Create Date: 2023-03-09 10:17:37.387897

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'bb07e4fc3fe8'
down_revision = 'c720631c996d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
