"""add status columns for syncs and runs

Revision ID: c58623ba1185
Revises: bb07e4fc3fe8
Create Date: 2023-03-10 10:34:46.167113

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c58623ba1185'
down_revision = 'bb07e4fc3fe8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_runs', sa.Column('dagster_run_id', sa.Text(), nullable=False))
    op.add_column('sync_schedules', sa.Column('last_run_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('sync_schedules', sa.Column('run_status', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_schedules', 'run_status')
    op.drop_column('sync_schedules', 'last_run_id')
    op.drop_column('sync_runs', 'dagster_run_id')
    # ### end Alembic commands ###
