"""sync schedules and sync runs models revision

Revision ID: c720631c996d
Revises: 1fb208c0104d
Create Date: 2023-03-09 09:25:59.893362

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c720631c996d'
down_revision = '1fb208c0104d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_runs', sa.Column('status', sa.Text(), nullable=False))
    op.add_column('sync_runs', sa.Column('metrics', sa.JSON(), nullable=True))
    op.add_column('sync_runs', sa.Column('remarks', sa.JSON(), nullable=True))
    op.drop_column('sync_runs', 'run_status')
    op.drop_column('sync_runs', 'run_metrics')
    op.drop_column('sync_runs', 'run_remarks')
    op.add_column('sync_schedules', sa.Column('status', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_schedules', 'status')
    op.add_column('sync_runs', sa.Column('run_remarks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('sync_runs', sa.Column('run_metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('sync_runs', sa.Column('run_status', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('sync_runs', 'remarks')
    op.drop_column('sync_runs', 'metrics')
    op.drop_column('sync_runs', 'status')
    # ### end Alembic commands ###
