"""nullable dagster_run

Revision ID: e35bcb2ecd98
Revises: c58623ba1185
Create Date: 2023-03-10 11:09:11.463613

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'e35bcb2ecd98'
down_revision = 'c58623ba1185'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_runs', 'dagster_run_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_runs', 'dagster_run_id',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
