FROM python:3.7-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagit and dagster-daemon, and to load the DagsterInstance

RUN /usr/local/bin/python -m pip install --upgrade pip

RUN pip install \
    dagster==1.3.3 \
    dagster-postgres==0.19.3 \
    dagster-docker==0.19.3 \
    requests==2.28.1

# Add repository code

WORKDIR /opt/dagster/app

COPY valmi_repo /opt/dagster/app/valmi_repo

# Run dagster gRPC server on port 4001

EXPOSE 4001

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4001", "--module-name", "valmi_repo"]
LABEL io.valmi.version=0.1.0
