"""add timestamp to store

Revision ID: 7b8fdebf0bb2
Revises: 339a88b5b487
Create Date: 2023-02-16 17:30:39.288452

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '7b8fdebf0bb2'
down_revision = '339a88b5b487'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'timestamp')
    # ### end Alembic commands ###
