# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "valmi-io"
client_id = "5db5df37a622c4e10a9714a04ba038cc"
application_url = "https://fred-treat-virus-email.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_pixels,read_customer_events,read_customers,read_checkouts,read_orders,read_fulfillments,read_products"

[auth]
redirect_urls = [
  "https://fred-treat-virus-email.trycloudflare.com/auth/callback",
  "https://fred-treat-virus-email.trycloudflare.com/auth/shopify/callback",
  "https://fred-treat-virus-email.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-valmi-app.myshopify.com"
