# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "valmi.io data platform"
client_id = "5433cb46ca2e8e55679d1d257fc4ace7"
application_url = "https://control-doom-boot-say.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_pixels,read_customer_events,read_customers,read_checkouts,read_orders,read_fulfillments,read_products"

[auth]
redirect_urls = [
  "https://control-doom-boot-say.trycloudflare.com/auth/callback",
  "https://control-doom-boot-say.trycloudflare.com/auth/shopify/callback",
  "https://control-doom-boot-say.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-ca35a911.myshopify.com"
