# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "valmi-io"
client_id = "723f508680a0733c81c28412effa6d2b"
application_url = "https://being-ff-publication-mb.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_pixels,read_customer_events,read_customers,read_checkouts,read_orders,read_fulfillments,read_products"

[auth]
redirect_urls = [
  "https://being-ff-publication-mb.trycloudflare.com/auth/callback",
  "https://being-ff-publication-mb.trycloudflare.com/auth/shopify/callback",
  "https://being-ff-publication-mb.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-6ebc0909.myshopify.com"
