# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "valmi-io"
client_id = "723f508680a0733c81c28412effa6d2b"
application_url = "https://office-february-rhode-smallest.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_pixels,read_customer_events,read_customers,read_checkouts,read_orders,read_fulfillments"

[auth]
redirect_urls = [
  "https://office-february-rhode-smallest.trycloudflare.com/auth/callback",
  "https://office-february-rhode-smallest.trycloudflare.com/auth/shopify/callback",
  "https://office-february-rhode-smallest.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-6ebc0909.myshopify.com"
