# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "valmi-io"
client_id = "2ebb77********"
application_url = "https://two-highways-realty-additionally.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_pixels,read_customer_events,read_customers,read_checkouts,read_orders,read_fulfillments,read_products"

[auth]
redirect_urls = [
  "https://two-highways-realty-additionally.trycloudflare.com/auth/callback",
  "https://two-highways-realty-additionally.trycloudflare.com/auth/shopify/callback",
  "https://two-highways-realty-additionally.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-ca35a911.myshopify.com"
